### ISSUE TITLE
Most recent commit throwing error, Apr 26 commit fine

### ISSUE THREAD

**Issue by peteflorence** [RobotLocomotion/cmake#12]
Not an issue really, just a note for next time /drake points to a fresher /cmake commit.

With the most recent commit in RobotLocomotion/cmake, I got a "Could not find MEX_CC using mex -v" error for which a fix was documented at at https://github.com/RobotLocomotion/drake/issues/53

Running just the following commands in /drake fixed this issue

```
git submodule init
git submodule sync
git submodule update
```

To verify that it was just the cmake update that was the difference, I did make clean, went back into cmake, git pulled in cmake, tried to compile again and got the same "Could not find MEX_CC using mex -v" error.  I then made clean and redid the commands above in /drake and was able to make fine.

I'm also on Yosemite like in the issue linked above, and perhaps the fix for that got lost between the April 26 stable commit and the most recent one?

**Comment by RussTedrake** [comment]
Correct.  We updated the cmake submodule reference, and the above commands are exactly the right way to update.  I do a 
'''
git submodule update --init --recursive 
'''
Basically every time i update drake (or any repo w/ submodules)
